export { CartPage, CartPage as Cart } from './CartPage'
export { CheckoutPage, CheckoutPage as Checkout } from './CheckoutPage'
export { OrderDetailsPage, OrderDetailsPage as OrderDetails } from './OrderDetailsPage'
export { MyOrdersPage, MyOrdersPage as MyOrders } from './MyOrdersPage'
export { ProfilePage, ProfilePage as Profile } from './ProfilePage'
